---
title: 'Chapter3: Probability Basics'
author: "Chenfeng Hao"
date: "9/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load all packages here:
library(tidyverse)
library(dplyr)
library(ggplot2)
# Set seed value of random number generator to get "replicable" random numbers.
# The choice of seed value of 76 was an arbitrary one on my part.
set.seed(76)
```

```{r}
stratum = 1:3
label = c('United States', 'Mexico', 'Canada')
population = c(310, 112, 34)
averageAge = c(36.8, 26.7, 40.7)
#put vectors in a tibble to display
tibble(stratum, label, population, averageAge)
```

```{r}
averageNA = (population / sum(population)) %*% averageAge
round(averageNA, 1)
```

```{r}
x1 = c(-1, 0, 1)
x0 = rep(1, 3)
X = matrix(c(x0, x1), 3, 2)
X
```

```{r}
betahat=c(46.3,3.0)
yhat=X%*%betahat
yhat
```

```{r}
curve(46.3+3.0*x, from=-1, to=5)
```

```{r}
population=tribble(
~height, ~eyecolor, ~p,
"T", "Bl", .12,
"T", "Br", .15,
"T", "G", .03,
"M", "Bl", .22,
"M", "Br", .34,
"M", "G", .04,
"S", "Bl", .06,
"S", "Br", .01,
"S", "G", .03)
population
```

```{r}
dice = 1:6
sample(x = dice, size = 1, replace = TRUE)
```

```{r}
sims = sample(x = dice, size = 1000, replace = TRUE)
table(sims) / length(sims)
plot(table(sims), xlab = 'roll', ylab = 'Frequency', main = '1000 Rolls of 1 Fair Dice')
```

```{r}
test <- c(1,2,3,4)
test1 <- sum((test - 2.5) ^ 2 / 4)
sqrt(test1)
```

